"""
Data Generation and Loading for Invariant DLR

This module provides:
1. Synthetic data generation using IEEE 738 physics
2. Data normalization utilities
3. PyTorch Dataset and DataLoader creation

The synthetic data is physics-accurate, generated by solving the
IEEE 738 heat balance equation for various conditions.

Author: Dr. Gelavizh Ahmadi
Copyright (c) 2026 Invariant Energy GmbH
"""

import torch
import numpy as np
import pandas as pd
from torch.utils.data import Dataset, DataLoader
from typing import Tuple, Optional, Dict, List
from dataclasses import dataclass
import json
from pathlib import Path

from .physics import IEEE738HeatBalance


@dataclass
class DataConfig:
    """Configuration for data generation"""
    
    # Ambient temperature range (°C)
    T_ambient_min: float = -15.0
    T_ambient_max: float = 42.0
    
    # Wind speed range (m/s)
    wind_speed_min: float = 0.3
    wind_speed_max: float = 18.0
    
    # Wind angle range (degrees from perpendicular)
    wind_angle_min: float = 0.0
    wind_angle_max: float = 90.0
    
    # Solar irradiance range (W/m²)
    solar_min: float = 0.0
    solar_max: float = 1100.0
    
    # Current range (A)
    current_min: float = 150.0
    current_max: float = 1400.0
    
    # Noise levels for realistic data
    temp_noise_std: float = 0.5  # °C
    rating_noise_std: float = 5.0  # A


class InputNormalizer:
    """
    Normalize inputs to zero mean, unit variance
    
    Stores normalization parameters for inference.
    """
    
    def __init__(self):
        # Default normalization parameters (can be updated with fit())
        self.mean = np.array([15.0, 5.0, 45.0, 500.0, 700.0, 7.283e-5])
        self.std = np.array([15.0, 4.0, 30.0, 350.0, 350.0, 2e-5])
        self.feature_names = [
            'T_ambient', 'wind_speed', 'wind_angle', 
            'solar_irradiance', 'current', 'resistance'
        ]
    
    def fit(self, data: np.ndarray) -> 'InputNormalizer':
        """Compute normalization parameters from data"""
        self.mean = data.mean(axis=0)
        self.std = data.std(axis=0)
        self.std[self.std < 1e-8] = 1.0  # Prevent division by zero
        return self
    
    def transform(self, data: np.ndarray) -> np.ndarray:
        """Normalize data"""
        return (data - self.mean) / self.std
    
    def inverse_transform(self, data: np.ndarray) -> np.ndarray:
        """Denormalize data"""
        return data * self.std + self.mean
    
    def save(self, path: str):
        """Save normalization parameters"""
        params = {
            'mean': self.mean.tolist(),
            'std': self.std.tolist(),
            'feature_names': self.feature_names,
        }
        with open(path, 'w') as f:
            json.dump(params, f, indent=2)
    
    def load(self, path: str) -> 'InputNormalizer':
        """Load normalization parameters"""
        with open(path, 'r') as f:
            params = json.load(f)
        self.mean = np.array(params['mean'])
        self.std = np.array(params['std'])
        self.feature_names = params['feature_names']
        return self


class SyntheticDLRDataset(Dataset):
    """
    Synthetic dataset for DLR training
    
    Generates physics-accurate data using IEEE 738 equations.
    Ground truth is computed by solving the heat balance equation.
    """
    
    def __init__(
        self,
        n_samples: int = 10000,
        physics: Optional[IEEE738HeatBalance] = None,
        config: Optional[DataConfig] = None,
        seed: int = 42,
        add_noise: bool = True,
    ):
        """
        Generate synthetic DLR dataset
        
        Args:
            n_samples: Number of samples to generate
            physics: IEEE738HeatBalance instance (creates default if None)
            config: DataConfig for ranges (uses defaults if None)
            seed: Random seed for reproducibility
            add_noise: Add realistic measurement noise
        """
        np.random.seed(seed)
        torch.manual_seed(seed)
        
        self.n_samples = n_samples
        self.physics = physics or IEEE738HeatBalance()
        self.config = config or DataConfig()
        self.add_noise = add_noise
        
        # Generate random conditions
        self._generate_data()
        
        # Setup normalizer
        self.normalizer = InputNormalizer()
        raw_inputs = np.column_stack([
            self.T_ambient, self.wind_speed, self.wind_angle,
            self.solar_irradiance, self.current,
            np.full(n_samples, self.physics.R_ref.item())
        ])
        self.normalizer.fit(raw_inputs)
    
    def _generate_data(self):
        """Generate all data samples"""
        cfg = self.config
        n = self.n_samples
        
        # Sample conditions with realistic distributions
        # Temperature: slightly favor moderate temperatures
        self.T_ambient = np.random.triangular(
            cfg.T_ambient_min, 20.0, cfg.T_ambient_max, n
        )
        
        # Wind: log-normal distribution (most days have light wind)
        wind_raw = np.random.lognormal(mean=1.0, sigma=0.8, size=n)
        self.wind_speed = np.clip(wind_raw, cfg.wind_speed_min, cfg.wind_speed_max)
        
        # Wind angle: uniform
        self.wind_angle = np.random.uniform(cfg.wind_angle_min, cfg.wind_angle_max, n)
        
        # Solar: bimodal (day vs night)
        is_day = np.random.random(n) > 0.3  # 70% daytime samples
        self.solar_irradiance = np.where(
            is_day,
            np.random.uniform(200, cfg.solar_max, n),
            np.random.uniform(0, 50, n)
        )
        
        # Current: favor moderate to high loads
        self.current = np.random.triangular(
            cfg.current_min, 600, cfg.current_max, n
        )
        
        # Convert to tensors for physics calculations
        T_amb_t = torch.tensor(self.T_ambient, dtype=torch.float32)
        wind_t = torch.tensor(self.wind_speed, dtype=torch.float32)
        angle_t = torch.tensor(self.wind_angle, dtype=torch.float32)
        solar_t = torch.tensor(self.solar_irradiance, dtype=torch.float32)
        current_t = torch.tensor(self.current, dtype=torch.float32)
        
        # Calculate ground truth using physics (steady-state solution)
        with torch.no_grad():
            self.T_conductor = self.physics.steady_state_temperature(
                current=current_t,
                T_ambient=T_amb_t,
                wind_speed=wind_t,
                solar_irradiance=solar_t,
                wind_angle=angle_t,
            ).numpy()
            
            # Calculate ampacity at standard max temp (75°C)
            self.ampacity = self.physics.ampacity(
                T_max=75.0,
                T_ambient=T_amb_t,
                wind_speed=wind_t,
                solar_irradiance=solar_t,
                wind_angle=angle_t,
            ).numpy()
        
        # Add realistic measurement noise
        if self.add_noise:
            self.T_conductor += np.random.normal(0, self.config.temp_noise_std, n)
            self.ampacity += np.random.normal(0, self.config.rating_noise_std, n)
        
        # Clamp to valid ranges
        self.T_conductor = np.clip(self.T_conductor, self.T_ambient, 150)
        self.ampacity = np.clip(self.ampacity, 100, 3000)
    
    def __len__(self) -> int:
        return self.n_samples
    
    def __getitem__(self, idx: int) -> Tuple[torch.Tensor, torch.Tensor]:
        """
        Get normalized input and target for training
        
        Returns:
            x: Normalized input features [6]
            y: Targets [temperature, ampacity]
        """
        # Build input vector
        x = np.array([
            self.T_ambient[idx],
            self.wind_speed[idx],
            self.wind_angle[idx],
            self.solar_irradiance[idx],
            self.current[idx],
            self.physics.R_ref.item(),
        ])
        
        # Normalize
        x_norm = self.normalizer.transform(x)
        
        # Targets
        y = np.array([
            self.T_conductor[idx],
            self.ampacity[idx],
        ])
        
        return (
            torch.tensor(x_norm, dtype=torch.float32),
            torch.tensor(y, dtype=torch.float32),
        )
    
    def get_raw_inputs(self, idx: int) -> Dict[str, float]:
        """Get unnormalized inputs (for physics calculations)"""
        return {
            'T_ambient': self.T_ambient[idx],
            'wind_speed': self.wind_speed[idx],
            'wind_angle': self.wind_angle[idx],
            'solar_irradiance': self.solar_irradiance[idx],
            'current': self.current[idx],
        }
    
    def get_batch_raw(
        self, 
        indices: List[int]
    ) -> Dict[str, torch.Tensor]:
        """Get batch of raw inputs as tensors"""
        return {
            'T_ambient': torch.tensor([self.T_ambient[i] for i in indices], dtype=torch.float32),
            'wind_speed': torch.tensor([self.wind_speed[i] for i in indices], dtype=torch.float32),
            'wind_angle': torch.tensor([self.wind_angle[i] for i in indices], dtype=torch.float32),
            'solar_irradiance': torch.tensor([self.solar_irradiance[i] for i in indices], dtype=torch.float32),
            'current': torch.tensor([self.current[i] for i in indices], dtype=torch.float32),
        }
    
    def get_statistics(self) -> Dict[str, Dict[str, float]]:
        """Get dataset statistics"""
        return {
            'T_ambient': {'min': self.T_ambient.min(), 'max': self.T_ambient.max(), 'mean': self.T_ambient.mean()},
            'wind_speed': {'min': self.wind_speed.min(), 'max': self.wind_speed.max(), 'mean': self.wind_speed.mean()},
            'wind_angle': {'min': self.wind_angle.min(), 'max': self.wind_angle.max(), 'mean': self.wind_angle.mean()},
            'solar_irradiance': {'min': self.solar_irradiance.min(), 'max': self.solar_irradiance.max(), 'mean': self.solar_irradiance.mean()},
            'current': {'min': self.current.min(), 'max': self.current.max(), 'mean': self.current.mean()},
            'T_conductor': {'min': self.T_conductor.min(), 'max': self.T_conductor.max(), 'mean': self.T_conductor.mean()},
            'ampacity': {'min': self.ampacity.min(), 'max': self.ampacity.max(), 'mean': self.ampacity.mean()},
        }


class CollateWithRaw:
    """
    Custom collate function that includes raw inputs for physics loss
    """
    
    def __init__(self, dataset: SyntheticDLRDataset):
        self.dataset = dataset
    
    def __call__(self, batch):
        # Standard collation
        x_list, y_list = zip(*batch)
        x = torch.stack(x_list)
        y = torch.stack(y_list)
        
        # Get indices (this is a bit hacky, but works)
        # In practice, we'll denormalize x to get raw inputs
        return x, y


def create_dataloaders(
    n_train: int = 15000,
    n_val: int = 3000,
    batch_size: int = 256,
    num_workers: int = 0,
    seed: int = 42,
) -> Tuple[DataLoader, DataLoader, SyntheticDLRDataset, SyntheticDLRDataset]:
    """
    Create training and validation dataloaders
    
    Args:
        n_train: Number of training samples
        n_val: Number of validation samples
        batch_size: Batch size
        num_workers: DataLoader workers (0 for M1/M2 Mac)
        seed: Random seed
        
    Returns:
        train_loader: Training DataLoader
        val_loader: Validation DataLoader
        train_dataset: Training dataset (for accessing normalizer)
        val_dataset: Validation dataset
    """
    # Create datasets with different seeds
    train_dataset = SyntheticDLRDataset(
        n_samples=n_train, 
        seed=seed,
        add_noise=True
    )
    val_dataset = SyntheticDLRDataset(
        n_samples=n_val, 
        seed=seed + 1000,  # Different seed for validation
        add_noise=True
    )
    
    # Use same normalizer for both
    val_dataset.normalizer = train_dataset.normalizer
    
    # Create dataloaders
    train_loader = DataLoader(
        train_dataset,
        batch_size=batch_size,
        shuffle=True,
        num_workers=num_workers,
        pin_memory=True,
        drop_last=True,
    )
    
    val_loader = DataLoader(
        val_dataset,
        batch_size=batch_size,
        shuffle=False,
        num_workers=num_workers,
        pin_memory=True,
    )
    
    return train_loader, val_loader, train_dataset, val_dataset


def denormalize_batch(
    x_norm: torch.Tensor,
    normalizer: InputNormalizer,
) -> Dict[str, torch.Tensor]:
    """
    Denormalize a batch of inputs back to physical values
    
    Args:
        x_norm: Normalized inputs [batch, 6]
        normalizer: InputNormalizer instance
        
    Returns:
        Dictionary of denormalized inputs
    """
    # Convert to numpy for denormalization
    x_np = x_norm.cpu().numpy()
    x_raw = normalizer.inverse_transform(x_np)
    
    # Convert back to tensors
    device = x_norm.device
    return {
        'T_ambient': torch.tensor(x_raw[:, 0], dtype=torch.float32, device=device),
        'wind_speed': torch.tensor(x_raw[:, 1], dtype=torch.float32, device=device),
        'wind_angle': torch.tensor(x_raw[:, 2], dtype=torch.float32, device=device),
        'solar_irradiance': torch.tensor(x_raw[:, 3], dtype=torch.float32, device=device),
        'current': torch.tensor(x_raw[:, 4], dtype=torch.float32, device=device),
    }


# Quick test
if __name__ == "__main__":
    print("Creating synthetic dataset...")
    dataset = SyntheticDLRDataset(n_samples=1000)
    
    print("\nDataset statistics:")
    stats = dataset.get_statistics()
    for key, values in stats.items():
        print(f"  {key}: min={values['min']:.1f}, max={values['max']:.1f}, mean={values['mean']:.1f}")
    
    print("\nSample data:")
    x, y = dataset[0]
    print(f"  Input (normalized): {x}")
    print(f"  Output: T_conductor={y[0]:.1f}°C, ampacity={y[1]:.0f}A")
    
    print("\nCreating dataloaders...")
    train_loader, val_loader, train_ds, val_ds = create_dataloaders(
        n_train=5000, n_val=1000, batch_size=128
    )
    print(f"  Train batches: {len(train_loader)}")
    print(f"  Val batches: {len(val_loader)}")
    
    # Test batch
    x_batch, y_batch = next(iter(train_loader))
    print(f"\nBatch shapes: x={x_batch.shape}, y={y_batch.shape}")
